In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

%matplotlib inline

In [2]:
# veri kaynağı: http://veribilimi.co/data/iris.csv
df = pd.read_csv("D:\\Datasets\\adult_preprocessed.csv")

# 1. Veri keşfi

In [3]:
df.head()

workclass  education education_merged      marital_status  \
0         State-gov  Bachelors   Under-Graduate       Never-married   
1  Self-emp-not-inc  Bachelors   Under-Graduate  Married-civ-spouse   
2           Private    HS-grad          HS-grad            Divorced   
3           Private       11th      High-School  Married-civ-spouse   
4           Private  Bachelors   Under-Graduate  Married-civ-spouse   

          occupation   relationship   race     sex native_country  age  \
0       Adm-clerical  Not-in-family  White    Male  United-States   39   
1    Exec-managerial        Husband  White    Male  United-States   50   
2  Handlers-cleaners  Not-in-family  White    Male  United-States   38   
3  Handlers-cleaners        Husband  Black    Male  United-States   53   
4     Prof-specialty           Wife  Black  Female           Cuba   28   

     fnlwgt  education_num  capital_gain  capital_loss  hours_per_week output  
0   77516.0           13.0        2174.0           0.0            40.0  <=50K  
1   83311.0           13.0           0.0           0.0            13.0  <=50K  
2  215646.0            9.0           0.0           0.0            40.0  <=50K  
3  234721.0            7.0           0.0           0.0            40.0  <=50K  
4  338409.0           13.0           0.0           0.0            40.0  <=50K

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45207 entries, 0 to 45206
Data columns (total 16 columns):
workclass           45207 non-null object
education           45207 non-null object
education_merged    45207 non-null object
marital_status      45207 non-null object
occupation          45207 non-null object
relationship        45207 non-null object
race                45207 non-null object
sex                 45207 non-null object
native_country      45207 non-null object
age                 45207 non-null int64
fnlwgt              45207 non-null float64
education_num       45207 non-null float64
capital_gain        45207 non-null float64
capital_loss        45207 non-null float64
hours_per_week      45207 non-null float64
output              45207 non-null object
dtypes: float64(5), int64(1), object(10)
memory usage: 5.5+ MB


In [5]:
# Boşluk yok

In [6]:
# Veri keşfi ile başka birçok groupby, count_values vb. sorgular kullanılabilir. Grafikler çizilip incelenebilr.

# 2. Veri Temizliği ve Ön Hazırlığı

In [7]:
# Veri önceden temizlenmiş olduğundan bu aşamada birşey yapmıyoruz.

## 2.1. Veriyi X,y olarak bölme (nitelikler matrisi ve hedef değişken - dikey bölme)

In [8]:
# Hedef değişken en sonda olduğu için son indekse kadar tüm nitelikleri alıyoruz
X = df.iloc[:,:-1].values
X.shape

(45207, 15)

In [9]:
# Kontrol
X[:3]

array([['State-gov', 'Bachelors', 'Under-Graduate', 'Never-married',
        'Adm-clerical', 'Not-in-family', 'White', 'Male',
        'United-States', 39, 77516.0, 13.0, 2174.0, 0.0, 40.0],
       ['Self-emp-not-inc', 'Bachelors', 'Under-Graduate',
        'Married-civ-spouse', 'Exec-managerial', 'Husband', 'White',
        'Male', 'United-States', 50, 83311.0, 13.0, 0.0, 0.0, 13.0],
       ['Private', 'HS-grad', 'HS-grad', 'Divorced', 'Handlers-cleaners',
        'Not-in-family', 'White', 'Male', 'United-States', 38, 215646.0,
        9.0, 0.0, 0.0, 40.0]], dtype=object)

In [10]:
# En son indeks hedef değiken (output)
y = df.iloc[:,-1].values
y.shape

(45207,)

In [11]:
# Kontrol
y[:10]

array(['<=50K', '<=50K', '<=50K', '<=50K', '<=50K', '<=50K', '<=50K',
       '>50K', '>50K', '>50K'], dtype=object)

## 2.2. Kategorik Nitelik Dönüştürme

### 2.2.1. Girdi Nitelikler için LabelEncoder

In [12]:
# Her bir kategorik nitelik için ayrı bir LabelEncoder nesnesi yaratalım. 
# Tek bir nesne ile de yapabiliriz ancak bu durumda orjinal değerlere dönmek mümkün olmaz.
from sklearn.preprocessing import LabelEncoder
labelencoder_workclass = LabelEncoder()
labelencoder_education = LabelEncoder()
labelencoder_education_merged = LabelEncoder()
labelencoder_marital_status = LabelEncoder()
labelencoder_occupation = LabelEncoder()
labelencoder_relationship = LabelEncoder()
labelencoder_race = LabelEncoder()
labelencoder_sex = LabelEncoder()
labelencoder_native_country = LabelEncoder()

In [13]:
# Her bir kategorik nitelik için oluşturduğumuz LabelEncoder nesnelerini (makine) eğitip sonucu dönüştürüp string değerler
# ile dğiştiriyoruz. Artık X içinde string değer kalmıyor. Onların yerine nümerik karşılıkları var. Bu nümerik değerlerin
# orjinal veride hangi string değere karşılık geldiğini ilgili LabelEncoder nesnesi biliyor.
X[:,0] = labelencoder_workclass.fit_transform(X[:,0])
X[:,1] = labelencoder_education.fit_transform(X[:,1])
X[:,2] = labelencoder_education_merged.fit_transform(X[:,2])
X[:,3] = labelencoder_marital_status.fit_transform(X[:,3])
X[:,4] = labelencoder_occupation.fit_transform(X[:,4])
X[:,5] = labelencoder_relationship.fit_transform(X[:,5])
X[:,6] = labelencoder_race.fit_transform(X[:,6])
X[:,7] = labelencoder_sex.fit_transform(X[:,7])
X[:,8] = labelencoder_native_country.fit_transform(X[:,8])

In [14]:
X[:2]

array([[5, 9, 8, 4, 0, 1, 4, 1, 37, 39, 77516.0, 13.0, 2174.0, 0.0, 40.0],
       [4, 9, 8, 2, 2, 0, 4, 1, 37, 50, 83311.0, 13.0, 0.0, 0.0, 13.0]],
      dtype=object)

In [15]:
# Örnek olarak iki LabelEncoder eğitilmiş nesnesinin sınıflarını görelim
print(labelencoder_workclass.classes_)
print(labelencoder_education.classes_)

['Federal-gov' 'Local-gov' 'Private' 'Self-emp-inc' 'Self-emp-not-inc'
 'State-gov' 'Without-pay']
['10th' '11th' '12th' '1st-4th' '5th-6th' '7th-8th' '9th' 'Assoc-acdm'
 'Assoc-voc' 'Bachelors' 'Doctorate' 'HS-grad' 'Masters' 'Preschool'
 'Prof-school' 'Some-college']


In [16]:
# X'in boyut kontrolü. Değişme olmamalı
X.shape

(45207, 15)

In [18]:
original_sex = labelencoder_workclass.inverse_transform(X[:,0].astype(int))
type(original_sex)

numpy.ndarray

In [19]:
original_sex

array(['State-gov', 'Self-emp-not-inc', 'Private', ..., 'Private',
       'Private', 'Self-emp-inc'], dtype=object)

### 2.2.2. One Hot Encoder - ColumnTransformer

In [16]:
from sklearn.preprocessing import OneHotEncoder

In [17]:
onehotencoder = OneHotEncoder(handle_unknown='ignore', categories='auto')

In [18]:
# Birden sütunu ilgilendiren dönüşümleri kolay yapabilmek için kullanışlı bir sınıf (Estimator kökenli)
# Biz burada sadece OneHotEncoder için kullanacağız.
from sklearn.compose import ColumnTransformer

In [19]:
# one_hot_encode_with_ct bizim kendi verdiğiiz isimdir. onehotencoder'ı yukarıda yarattık. [0,1,2,3,4,5,6,7,8] ise dönüşecek
# niteliklerin indeks değerleridir.
ct = ColumnTransformer(
    [('one_hot_encode_with_ct', onehotencoder, [0,1,2,3,4,5,6,7,8]),], 
    remainder='passthrough'
)

In [20]:
# ColumnTransformer nesnesi ile onehotencoder nesnesini eğitip gerekli dönüşümleri gerçekleştirip X'e tekrar atayalım.
# Burada X'in boyutu(shape) değişecektir.
X = ct.fit_transform(X)

In [21]:
# Boyut değişmiş olmalı. Çnkü gölge değişkenler eklendi
X.shape

(45207, 111)

In [22]:
X[:10,:]

<10x111 sparse matrix of type '<class 'numpy.float64'>'
	with 133 stored elements in Compressed Sparse Row format>

In [23]:
# sparse matrix'i numpy.ndarray'a çevirelim. Çünkü sınıflandırıcı öyle istiyor.
X = X.toarray()

In [24]:
C

(45207, 111)

### 2.2.3. Hedef değişken için Label Encoder

In [25]:
# Hedef niteliği sadece LabelEncoder ile rakamlara kodluyoruz.
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

## 2.3. Feature Scaling (Standardizasyon)

In [26]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X = sc_X.fit_transform(X)

## 2.4. Veriyi eğitim ve test setlerine bölme (yatay bölme)

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=142)

In [29]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(33905, 111)
(33905,)
(11302, 111)
(11302,)


# 3. Model Oluşturma ve Eğitim

In [30]:
from sklearn.linear_model import LogisticRegression

In [31]:
classifier = LogisticRegression(random_state=142, solver='lbfgs')

In [32]:
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=142, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

# 4. Predictions

In [33]:
y_pred = classifier.predict(X_test)

## 4.1. Tahmin sonuçlarını numpy.ndarray'den dataframe yapma (incelemek daha kolay)

In [34]:
predictions = pd.DataFrame(data=y_pred,    # values
                index=range(len(y_pred)),    # 1st column as index
                   columns=['y_pred'])  # 1st row as the column names

# Sadece y_pred'den oluşan df'e test(gerçek) y_test'i sütun olarak ekleme
predictions['y_test'] = y_test
predictions.head()

y_pred  y_test
0       0       0
1       0       0
2       0       0
3       0       0
4       0       0

# 5. Model Değerlendirme

## 5.1. Hata Matrisi (Confusion Matrix)

In [35]:
from sklearn.metrics import confusion_matrix

In [36]:
cm = confusion_matrix(y_true=y_test, y_pred=y_pred)
print(cm)

[[7919  566]
 [1143 1674]]


## 5.2. Sınıflandırma Performansı Değerlendirme (Accuracy)

In [37]:
from sklearn.metrics import accuracy_score

In [38]:
accuracy = accuracy_score(y_true=y_test, y_pred=y_pred)
print("Accuracy: % {:10.2f}".format(accuracy*100)) 
# :10.2f ifadesi ondalık kısımda iki basamak göstermek için

Accuracy: %      84.88


## 5.4. Elle Accuracy hesaplama

In [39]:
errors = predictions[predictions['y_pred'] != predictions['y_test']]
errors.head()

y_pred  y_test
12       1       0
36       1       0
46       1       0
62       0       1
66       1       0

In [40]:
predictions[predictions['y_pred'] != predictions['y_test']].count()

y_pred    1709
y_test    1709
dtype: int64

In [41]:
len(y_test)

11302

In [42]:
accuracy = (len(y_test) - len(errors)) / len(y_test)
accuracy

0.8487878251636879

# 6. Modeli Saklama ve Tekrar Kullanma

In [43]:
# Saklamadan önce tüm veri seti ile modeli tekrar eğitelim

## 6.1. Tüm veri ile modeli son olarak eğitme

In [44]:
# Eğitim setlerinin X ve y olduğuna dikkat!!!
classifier_last = LogisticRegression(random_state=142, solver='lbfgs')
classifier_last.fit(X, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=142, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [45]:
# Çalışırlığının basit kontrolü. Modeli tekrar okuduktan sonra bu değerle karşılaştırma yapacağız.
classifier_last.intercept_

array([-1.96013265])

## 6.2. Modeli kaydetme

In [1]:
import joblib

In [47]:
# joblib.dump(sınıflandırıcı, "/dizin/saklamak_istedigimiz_isim.pkl")
joblib.dump(classifier_last, 
"D:/OneDrive/egitim/verilen/bogazici-compec-python-ml/08_classification/saved_models/04.logistic_regression_with_adult_mixed_attr.pkl")

['04.logistic_regression_with_adult_mixed_attr.pkl']

In [48]:
# Kaydedilen yere Dosya gezgini veya jupyter home'dan bir göz atalım. 

## 6.3. Modeli okuma

In [49]:
classifier_last_loaded = joblib.load("D:/OneDrive/egitim/verilen/bogazici-compec-python-ml/08_classification/saved_models/04.logistic_regression_with_adult_mixed_attr.pkl")

In [50]:
classifier_last_loaded.get_params

<bound method BaseEstimator.get_params of LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=142, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)>

In [51]:
classifier_last_loaded.intercept_

array([-1.96013265])