In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[10,20,30],[40,50,60]])
print(a)

[[1 2 3]
 [4 5 6]]


In [3]:
print(b)

[[10 20 30]
 [40 50 60]]


In [5]:
a*b

array([[ 10,  40,  90],
       [160, 250, 360]])

In [6]:
print(np.multiply(a,b))

[[ 10  40  90]
 [160 250 360]]


In [7]:
a+b

array([[11, 22, 33],
       [44, 55, 66]])

In [8]:
print(np.add(a,b))

[[11 22 33]
 [44 55 66]]


In [9]:
a-b

array([[ -9, -18, -27],
       [-36, -45, -54]])

In [10]:
print(np.subtract(a,b))

[[ -9 -18 -27]
 [-36 -45 -54]]


In [13]:
a/b

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

In [14]:
print(np.divide(a,b))

[[0.1 0.1 0.1]
 [0.1 0.1 0.1]]


In [15]:
a*b.T

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [16]:
# Yukarıdaki işlemler matris çarpımı değil. Her iki array içinde aynı pozisyonda olan elemanlar için geçerli işlemlerdir.

# Veri türünü değiştirerek matris oluşturma

In [11]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [12]:
print(x)

[[1. 2.]
 [3. 4.]]


In [13]:
print(y)

[[5. 6.]
 [7. 8.]]


# İki vektörün çarpımı inner product

In [14]:
v = np.array([9,10])
w = np.array([11, 12])

In [15]:
print(v.dot(w))

219


In [16]:
# Yukarıdaki işlem: (9*11) + (10*12) = 99 + 120 = 219

In [17]:
print(np.dot(v, w))

219


# İki matrisin çarpımı

In [18]:
print(x.dot(y))

[[19. 22.]
 [43. 50.]]


In [19]:
print(np.dot(x,y))

[[19. 22.]
 [43. 50.]]


# dot product boyutun önemi

In [20]:
x = np.array([[1,2],[3,4],[5,6],[7,8]], dtype=np.float64)
y = np.array([[10,11,12],[14,15,16],[17,18,19]], dtype=np.float64)

In [21]:
print(x)

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]


In [22]:
print(y)

[[10. 11. 12.]
 [14. 15. 16.]
 [17. 18. 19.]]


In [23]:
print(x.dot(y))

ValueError: shapes (4,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [24]:
x.shape

(4, 2)

In [25]:
y.shape

(3, 3)

In [26]:
# (4, 2) (3, 3) İlk matrisin sütun sayısı ikinci matrisin satır sayısına eşit olmadığından dot product mümkün değil

In [27]:
x = np.array([[1,2],[3,4],[5,6],[7,8]], dtype=np.float64)
y = np.array([[10,11,12],[14,15,16]], dtype=np.float64)

In [28]:
print(x)
print(y)

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
[[10. 11. 12.]
 [14. 15. 16.]]


In [29]:
x.shape

(4, 2)

In [30]:
y.shape

(2, 3)

In [31]:
print(x.dot(y))

[[ 38.  41.  44.]
 [ 86.  93. 100.]
 [134. 145. 156.]
 [182. 197. 212.]]


In [32]:
#[[(1*10+2*14)=38 (1*11+2*15)=41 (1*12+2*16)=44 ]
# [(3*10+4*14)=86 .......]
# [.......]
# [.......]]

# matris değerlerinin toplamı

In [33]:
# tüm değerlerin toplamı
print(np.sum(x))

36.0


In [34]:
# sadece sütunların toplamı: sonuç satır sayısı kadar vektör
print(np.sum(x, axis=1))

[ 3.  7. 11. 15.]


In [35]:
# sadece satırların toplamı: sonuç sütun sayısı kadar vektör
print(np.sum(x, axis=0))

[16. 20.]


# Matris scaler çarpımı

In [42]:
print(np.dot(x,2))

[[ 2.  4.]
 [ 6.  8.]
 [10. 12.]
 [14. 16.]]
