In [22]:
import pandas as pd
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

%matplotlib inline

In [23]:
# veri kaynağı: http://veribilimi.co/data/iris.csv
df = pd.read_csv("D:/OneDrive/egitim/verilen/bogazici-compec-python-ml/Datasets/iris.csv")

# Veri keşfi

In [24]:
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [25]:
df.groupby(['Species']).agg(['mean']).head()

SepalLengthCm SepalWidthCm PetalLengthCm PetalWidthCm
                         mean         mean          mean         mean
Species                                                              
Iris-setosa             5.006        3.418         1.464        0.244
Iris-versicolor         5.936        2.770         4.260        1.326
Iris-virginica          6.588        2.974         5.552        2.026

# Veriyi X,y olarak bölme (nitelikler matrisi ve hedef değişken - dikey bölme)

In [26]:
X = df.iloc[:,:-1].values
X.shape

(150, 4)

In [27]:
y = df.iloc[:,-1].values
y.shape

(150,)

# Kategorik Nitelik Dönüştürme

In [1]:
# kategorik nitelik yok

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=142)

In [30]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(112, 4)
(38, 4)
(112,)
(38,)


In [31]:
from sklearn.linear_model import LogisticRegression

In [32]:
classifier = LogisticRegression(random_state=142)

In [33]:
classifier.fit(X_train, y_train)

D:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=142, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [34]:
y_pred = classifier.predict(X_test)

## Tahmin sonuçlarını numpy.ndarray'den dataframe yapma (İncelemek daha Kolay)

In [35]:
predictions = pd.DataFrame(data=y_pred,    # values
                index=range(len(y_pred)),    # 1st column as index
                   columns=['y_pred'])  # 1st row as the column names

# Sadece y_pred'den oluşan df'e test(gerçek) y_test'i sütun olarak ekleme
predictions['y_test'] = y_test
predictions.head()

y_pred           y_test
0      Iris-setosa      Iris-setosa
1  Iris-versicolor  Iris-versicolor
2   Iris-virginica  Iris-versicolor
3   Iris-virginica   Iris-virginica
4  Iris-versicolor  Iris-versicolor

# Hata Matrisi (Confusion Matrix)

In [36]:
from sklearn.metrics import confusion_matrix

In [37]:
cm = confusion_matrix(y_true=y_test, y_pred=y_pred)
print(cm)

[[ 7  0  0]
 [ 0 14  3]
 [ 0  1 13]]


In [38]:
from sklearn.metrics import accuracy_score

In [39]:
accuracy = accuracy_score(y_true=y_test, y_pred=y_pred)
print("Accuracy: % {:10.2f}".format(accuracy*100)) 
# :10.2f ifadesi ondalık kısımda iki basamak göstermek için

Accuracy: %      89.47


# Elle Accuracy hesaplama

In [22]:
predictions[predictions['y_pred'] != predictions['y_test']]

y_pred           y_test
1    Iris-virginica  Iris-versicolor
2    Iris-virginica  Iris-versicolor
18  Iris-versicolor   Iris-virginica
19   Iris-virginica  Iris-versicolor
25  Iris-versicolor   Iris-virginica
34   Iris-virginica  Iris-versicolor

In [23]:
predictions[predictions['y_pred'] != predictions['y_test']].count()

y_pred    6
y_test    6
dtype: int64

In [24]:
len(y_test)

38

In [25]:
accuracy = (len(y_test) - 4) / len(y_test)
accuracy

0.8947368421052632

# Elle tahmin seti üretme

In [26]:
# test seti dışında elle tahmin seti oluşturalım
X_manual_test = np.array([4.0,4.0,4.0,4.0]).reshape(1,4)

# array shape mutlaka uygun olmalı
print(X_manual_test.shape)
print(X_test.shape)

(1, 4)
(38, 4)


In [27]:
classifier.predict(X_manual_test)

array(['Iris-virginica'], dtype=object)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)